name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t liatrio-apprentice-app .

      - name: Run Docker container
        run: docker run -d -p 80:3000 liatrio-apprentice-app

      - name: Run Liatrio verification
        uses: liatrio/github-actions/apprentice-action@master
