name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t liatrio-apprentice-app .

      - name: Run Docker container
        run: docker run -d -p 80:3000 liatrio-apprentice-app
      - name: Verify application is ready
        run: curl --fail --retry 10 --retry-delay 1 http://localhost/

      - name: Run Liatrio verification
        continue-on-error: true
        uses: liatrio/github-actions/apprentice-action@master

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Docker image
        run: docker tag liatrio-apprentice-app tpgotmotion/liatrio-apprentice-app:${{ github.run_number }}

      - name: Push Docker image
        run: docker push tpgotmotion/liatrio-apprentice-app:${{ github.run_number }}
